import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {config} from '@fortawesome/fontawesome-svg-core'
import React from "react";
import RequireAuth from "@atoms/RequireAuth";
import {classNames} from "@/utils/styling";

config.autoAddCss = false;

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html className="h-full" lang="en">
        <RequireAuth/>
        <body className={classNames(inter.className, "h-full")}>
        {children}
        </body>
        </html>
    )
}
